//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MCITTrainingAPP.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class LU_EmploymentLevel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LU_EmploymentLevel()
        {
            this.LU_EmploymentDegree = new HashSet<LU_EmploymentDegree>();
        }
    
        public int EmploymentLevelID { get; set; }
        public string EmploymentName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LU_EmploymentDegree> LU_EmploymentDegree { get; set; }
    }
}
