//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MCITTrainingAPP.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_Candidates_Courses
    {
        public int CandID { get; set; }
        public string CandWorkSector { get; set; }
        public string CandWorkDept { get; set; }
        public string CandWorkTitle { get; set; }
        public Nullable<int> CandSubMinistryID { get; set; }
        public Nullable<int> CandTrainingCourse { get; set; }
        public string CandCourseDuration { get; set; }
        public Nullable<int> CandCourseProvider { get; set; }
        public Nullable<int> CandCourseStudyMechanism { get; set; }
        public Nullable<int> CandEmploymentDegree { get; set; }
        public Nullable<System.DateTime> CandStartDate { get; set; }
        public Nullable<System.DateTime> CandEndDate { get; set; }
        public Nullable<bool> CandCapitalStatus { get; set; }
        public Nullable<int> CandFiscalYearID { get; set; }
        public Nullable<int> CandInfoID { get; set; }
    
        public virtual LU_CourseProvider LU_CourseProvider { get; set; }
        public virtual LU_EmploymentDegree LU_EmploymentDegree { get; set; }
        public virtual LU_StudyMechanism LU_StudyMechanism { get; set; }
        public virtual LU_TrainingCourse LU_TrainingCourse { get; set; }
        public virtual TBL_CandidatesInfo TBL_CandidatesInfo { get; set; }
        public virtual TBL_SubMinistry TBL_SubMinistry { get; set; }
        public virtual TBL_FiscalYear TBL_FiscalYear { get; set; }
    }
}
