//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MCITTrainingAPP.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_SubMinistry
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBL_SubMinistry()
        {
            this.TBL_Candidates_Courses = new HashSet<TBL_Candidates_Courses>();
        }
    
        public int SubMinistryID { get; set; }
        public string SubMinistryName { get; set; }
        public Nullable<int> MinistryID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBL_Candidates_Courses> TBL_Candidates_Courses { get; set; }
        public virtual TBL_Ministries TBL_Ministries { get; set; }
    }
}
